[package]
name = "clean_up_pc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winproc = "0.6.4"
tokio = { version = "1", features = ["full"] }
